export const products = [
    {
        id:0,
        productName:"Elma",
        img:"../assets/images/elma.jpg",
        price:1000
    },
    {
        id:1,
        productName:"Karpuz",
        img:"../assets/images/karpuz.jpg",
        price:300
    },
    {
        id:2,
        productName:"Telefon",
        img:"../assets/images/telefon.jpg",
        price:300
    },
    {
        id:3,
        productName:"Bisiklet",
        img:"../assets/images/bisiklet.jpg",
        price:300
    }
]